/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.Jugador;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JugadorPanel extends javax.swing.JPanel {

	/**
	 * Creates new form JugadorPanel
	 */
	public JugadorPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    nombreLabel = new javax.swing.JLabel();
    saldoLabel = new javax.swing.JLabel();
    encarceladoLabel = new javax.swing.JLabel();
    especuladorLabel = new javax.swing.JLabel();
    nombreJugadorField = new javax.swing.JTextField();
    saldoJugadorField = new javax.swing.JTextField();
    encarceladoJugadorField = new javax.swing.JTextField();
    especuladorJugadorField = new javax.swing.JTextField();

    nombreLabel.setText("Nombre");
    nombreLabel.setEnabled(false);

    saldoLabel.setText("Saldo");
    saldoLabel.setEnabled(false);

    encarceladoLabel.setText("Encarcelado");
    encarceladoLabel.setEnabled(false);

    especuladorLabel.setText("Especulador");
    especuladorLabel.setEnabled(false);

    nombreJugadorField.setText("nombreJugador");
    nombreJugadorField.setEnabled(false);
    nombreJugadorField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nombreJugadorFieldActionPerformed(evt);
      }
    });

    saldoJugadorField.setText("saldoJugador");
    saldoJugadorField.setEnabled(false);

    encarceladoJugadorField.setText("encarceladoJugador");
    encarceladoJugadorField.setEnabled(false);

    especuladorJugadorField.setText("especuladorJugador");
    especuladorJugadorField.setEnabled(false);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(36, 36, 36)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(especuladorLabel)
            .addGap(18, 18, 18)
            .addComponent(especuladorJugadorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(encarceladoLabel)
            .addGap(18, 18, 18)
            .addComponent(encarceladoJugadorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(saldoLabel)
            .addGap(18, 18, 18)
            .addComponent(saldoJugadorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(nombreLabel)
            .addGap(18, 18, 18)
            .addComponent(nombreJugadorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(119, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(57, 57, 57)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(nombreLabel)
          .addComponent(nombreJugadorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(31, 31, 31)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(saldoLabel)
          .addComponent(saldoJugadorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(37, 37, 37)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(encarceladoLabel)
          .addComponent(encarceladoJugadorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(38, 38, 38)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(especuladorLabel)
          .addComponent(especuladorJugadorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(45, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void nombreJugadorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreJugadorFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_nombreJugadorFieldActionPerformed

	void setJugador(Jugador j){
		jugador = j;
		
		nombreJugadorField.setText(jugador.getNombre());
		saldoJugadorField.setText("El saldo es: " + jugador.getSaldo());
		encarceladoJugadorField.setText("Esta encarcelado: " + jugador.isEncarcelado());
		especuladorJugadorField.setText("Es especulador: " + jugador.)
	}
	
	private Jugador jugador;
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField encarceladoJugadorField;
  private javax.swing.JLabel encarceladoLabel;
  private javax.swing.JTextField especuladorJugadorField;
  private javax.swing.JLabel especuladorLabel;
  private javax.swing.JTextField nombreJugadorField;
  private javax.swing.JLabel nombreLabel;
  private javax.swing.JTextField saldoJugadorField;
  private javax.swing.JLabel saldoLabel;
  // End of variables declaration//GEN-END:variables
}
